FROM golang:1.22.4 AS builder
WORKDIR /src
COPY . /src
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /build/app cmd/zd/main.go

FROM alpine AS runner
WORKDIR /app
COPY --from=builder /build/app .
ENTRYPOINT ["./app"]